### ISSUE TITLE
Proper way to sort with a tmpdir?

### ISSUE THREAD

**Issue by cmdcolin** [ldubos/external-sorting#10]
Hi there

I was wondering if there is a proper way to sort with a tmpdir

If I have code like this

```
  const tmp = require('tmp')

  const tmpdir = tmp.dirSync({
    prefix: "mytmp",
  });

  const out = fs.createWriteStream(outIxFilename);

  await esort({
    input: input,
    output: out,
    tempDir: tmpdir.name,
  }).asc();
```

occasionally this gives

```
ENOENT: no such file or directory, open '/tmp/mytmp-1461688-vWg1Hpu7aYIL/2.tmp' 
```

I wasn't sure if this is my usage of tmp or this module. Thanks for this package!

**Comment by cmdcolin** [comment]
one possible helper...not sure cause it is intermittent failure but seems less common to run into this...maybe! :)

```
const streamFinished = promisify(finished);
import { promisify } from "util";
import { finished, Readable, PassThrough, Transform } from "stream";
const tmp = require("tmp");

const tmpdir = tmp.dirSync({
  prefix: "mytmp",
});

const out = fs.createWriteStream(outIxFilename);

await esort({
  input: input,
  output: out,
  tempDir: tmpdir.name,
}).asc();
await streamFinished(out);

```

**Comment by cmdcolin** [comment]
Sometimes the await streamFinished never completes so causes failure too. would be interested in what you think

**Comment by cmdcolin** [comment]
One possibility, wait for stream close instead of stream finish, but that could indicate an underlying bug

from stackoverflow https://stackoverflow.com/questions/37837132/how-to-wait-for-a-stream-to-finish-piping-nodejs "Note for others: the finish event only triggers if the caller handles the stream properly. If not (e.g. AWS SDK S3 uploads) then you can use the close event instead, to avoid the await sitting there forever. – "

**Comment by ldubos** [comment]
Hi, FYI in my code I'm listening to the `end` event (triggered when the `close` event is fired) and send an `end` event when it's finished. But I probably need to use the `close` event, I think we don't have any guarantees to have an `end` event from all readable streams (except for the node's events). What do you use as input stream ? It can help to understand what happen in this case

**Comment by cmdcolin** [comment]
Thanks for letting me know...I had a lot of moving variables but this was the code that definitely had this original issue with the 

ENOENT: no such file or directory, open '/tmp/mytmp-1461688-vWg1Hpu7aYIL/2.tmp' 


https://github.com/GMOD/ixixx-js/blob/v1.0.15/src/index.ts#L80-L171

as far as I know it was fundamentally just doing this

```

  const tmpdir = tmp.dirSync({
    prefix: "jbrowse-trix-sort",
    unsafeCleanup: true,
  });
  const tmpobj = tmp.fileSync({
    prefix: "jbrowse-trix-in",
    postfix: ".txt",
  });

  const tmpobj2 = tmp.fileSync({
    prefix: "jbrowse-trix-out",
    postfix: ".txt",
  });
  /* block of code that writes to tmpobj.name here */

  const inSort = fs.createReadStream(tmpobj.name);
  const outSort = fs.createWriteStream(tmpobj2.name);

  await esort({
    input: inSort,
    output: outSort,
    tempDir: tmpdir.name,
  }).asc();

    tmpobj.removeCallback();
    tmpobj2.removeCallback();
    tmpdir.removeCallback();

```

That led me to believe that it was somehow still accessing some files from disk when the esort was ended

I changed up the code in a way that appears to fix the "no such file or directory" and uses crazy input/output transforms...i think it works much better now but I really need to level up my streams understanding still https://github.com/GMOD/ixixx-js/blob/master/src/index.ts#L114-L139 (links to actual source code just posted for fun :))

**Comment by cmdcolin** [comment]
I was continuing to see some issues with this even after I was not removing the tmpdir at all (my previous hypothesis was that it was cleaning up the tmpdir too soon, but now my code doesn't even clean up the tmpdir and still has intermittent errors about `ENOENT: no such file or directory, open '/tmp/mytmp-1461688-vWg1Hpu7aYIL/2.tmp'` )

Do you think this error could be coming from this module?

I looked at some articles on the web like https://nodesource.com/blog/understanding-streams-in-nodejs/ but I couldn't get it to wait for  e.g. `await finished(writable);` (would fail tests in this module)

**Comment by ldubos** [comment]
Hello I just published a new version, can you test it and check if it fix your issue ?

**Comment by cmdcolin** [comment]
thanks so much! running tests now

**Comment by cmdcolin** [comment]
managed to complete 1000 test suite runs with no failures

maybe we can optimistically close now! super big thanks

**Comment by ldubos** [comment]
it's good to hear it 👍 I close the ticket
